### ISSUE TITLE
ffn_inference_colab_demo issue

### ISSUE THREAD

**Issue by ShixuanGu** [google/ffn#53]
IndexError                                Traceback (most recent call last)
[<ipython-input-13-2aca8bb0076d>](https://localhost:8080/#) in <cell line: 6>()
      4 else:
      5   vis_update = 1
----> 6 canvas.segment_at((125, 125, 125), dynamic_image=inference.DynamicImage(),vis_update_every=vis_update)

1 frames
[/content/ffn/ffn/inference/inference.py](https://localhost:8080/#) in update_at(self, pos, start_pos)
    411       end = start + self._input_seed_size
    412       logit_seed = np.array(
--> 413           self.seed[[slice(s, e) for s, e in zip(start, end)]])
    414       init_prediction = np.isnan(logit_seed)
    415       logit_seed[init_prediction] = np.float32(self.options.pad_value)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by mjanusz** [comment]
Thank you for the bug report. This has been fixed now -- sorry about the breakage!

**Comment by chenglily123** [comment]
Traceback (most recent call last):
  File "G:\ffn\ffn-master\notebooks\ffn\run_inference.py", line 60, in <module>
    app.run(main)
  File "C:\conda\envs\ffn-3.10\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\conda\envs\ffn-3.10\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "G:\ffn\ffn-master\notebooks\ffn\run_inference.py", line 51, in main
    runner.run((bbox.start.z, bbox.start.y, bbox.start.x),
  File "G:\ffn\ffn-master\notebooks\ffn\ffn\inference\runner.py", line 533, in run
    canvas.segment_all(
  File "G:\ffn\ffn-master\notebooks\ffn\ffn\inference\inference.py", line 550, in segment_all
    self.seed_policy.set_state(self._seed_policy_state)
  File "G:\ffn\ffn-master\notebooks\ffn\ffn\inference\seed.py", line 109, in set_state
    self.coords, self.idx = state
TypeError: iteration over a 0-d array
